// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'code': string;
  'codeTextArea': string;
  'container': string;
  'preview': string;
  'resize-handle': string;
}
export const cssExports: CssExports;
export default cssExports;
